config/routes.rb
Rails.application.routes.draw do
    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :teachers
  devise_for :users
  # namespace :user do
    resources :users do 
      member do
        get :all_courses, to: 'users#all_courses'
        get :transcript, to: 'users#transcript'

      end

      end

  #   root 'users#index'
  # end
  resources:teachers do
    member do
      get :prev_courses, to: 'teachers#prev_courses'
      get :current_courses, to: 'teachers#current_courses'
    end
  end

# Defines the root path route ("/")
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/batch.rb
class Batch < ApplicationRecord
has_many :users
end

app/models/course.rb
class Course < ApplicationRecord

has_many :sections


def to_s
 course_name
end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
belongs_to :user
belongs_to :grade
belongs_to :semester
belongs_to :section
end

app/models/grade.rb
class Grade < ApplicationRecord
    has_many :enrollments

    def to_s
        letter
    end


end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :teacher
    belongs_to :course
    belongs_to :semester
    
    has_many :enrollments

    def to_s
    section_name
    end

end
    

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :student_semesters
    has_many :students, through: :student_semesters
    has_many :enrollments
    has_many :sections

    def to_s
        semester_number.to_s + semester_type
    end
end

app/models/student_semester.rb
class StudentSemester < ApplicationRecord
  belongs_to :user
  belongs_to :semester
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sections
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         has_many :student_semesters, dependent: :destroy
         has_many :semesters, through: :student_semesters
         has_many   :enrollments
         belongs_to :batch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
        before_action :authenticate_teacher!
      
        # GET /teachers or /teachers.json
        def index
          @teachers = Teacher.all
        end
      
        # GET /teachers/1 or /teachers/1.json
        def show
        end
        def create
        end
      
        def prev_courses
          @teacher_sections=current_teacher.sections
          
        end
        
        def current_courses
          @teacher_sections=current_teacher.sections
        
        end
          
          private
        # Use callbacks to share common setup or constraints between actions.
        def set_teacher
          @teacher = Teacher.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def teacher_params
          params.require(:teacher).permit(:email,:password,:password_confirmation)
        end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
  end
    def index
        
    end

    def show
        # @user=current_user.id
        
    end

    def all_courses
        @enrollments=current_user.enrollments.where(grade_id:11)             
    end
  
    def transcript 
        @enrollments=current_user.enrollments.where.not(grade_id:11)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Soft LMS', root_path, class:"navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <% if user_signed_in? %>
        
        <li class="nav-item p-2">
        <%= link_to "Sign Out",destroy_user_session_path, method: "delete", class:"nav-link" %>
        </li>
        <% else %>    
       

        <li class="nav-item p-2">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>

        <% if teacher_signed_in? %>

        <li class="nav-item p-2">
        <%= link_to "Sign Out",destroy_user_session_path, method: "delete", class:"nav-link" %>
        </li>        
       <% else %>
            <li class="nav-item p-2">
          <%= link_to "Sign In As a teacher", new_teacher_session_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>

    </form>

  </div>

</nav>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="jumbotron container">
    <h1 class="display-4">Welcome to Our LMS</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoftLms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/header' %>

    <%= yield %>
  </body>
</html>

app/views/teachers/current_courses.html.erb
<h1>Current courses</h1>

<table id="enrollment" border="3" layout= "fixed" width=" 100%" >
<tr>
<th>ID</th>
<th>Course</th>
<th>Section</th>
<th>Semester Type</th>
<th>Semester No</th>

</tr>


<% @teacher_sections.each do |t| %>
    <tr>      
    <td><%= t.id %></td>
    <td><%= t.course.course_name %></td>
    <td><%= t.section_name %></td>
    <td><%= t.semester.semester_number%></td>
    <td><%= t.semester.semester_type%></td>
    </tr>      
<% end %>
    

app/views/teachers/index.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= teachers_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      
      <li class="nav-item">
        <a class="nav-link active " href="<%=teacher_path(current_teacher.id)%>" >Profile</a>
      </li>
      
      <li class="nav-item">
      <a class="nav-link active " href="<%=current_courses_teacher_path(current_teacher.id)%>" > Courses</a>
      </li>

      <li class="nav-item">
      <a class="nav-link active " href="<%=prev_courses_teacher_path(current_teacher.id)%>" >Prev Courses</a>
      </li>
      
      <li class="nav-item">
          <a class="nav-link active " href="<%= destroy_teacher_session_path %>" >Logout</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/teachers/prev_courses.html.erb
<h1>Previous courses</h1>


<table id="enrollment" border="3" layout= "fixed" width=" 100%" >
<tr>
<th>ID</th>
<th>Course</th>
<th>Section</th>
<th>Semester No</th>
<th>Semester Type</th>


</tr>

    <% @teacher_sections.each do |t| %>
        <tr>      
        <td><%= t.id %></td>
        <td><%= t.course.course_name %></td>
        <td><%= t.section_name %></td>
        <td><%= t.semester.semester_number%></td>
        <td><%= t.semester.semester_type%></td>
        
        </tr>      
 <% end %>
        

app/views/teachers/prevcourses.html.erb
<h1>Previous courses</h1>


<table id="enrollment" border="3" layout= "fixed" width=" 100%" >
<tr>
<th>ID</th>
<th>Course</th>
<th>Section</th>
<th>Semester No</th>
<th>Semester Type</th>
</tr>

    <% @teacher_sections.each do |t| %>
        <tr>      
        <td><%= t.id %></td>
            
        <td><%= t.course.course_name %></td>
        <td><%= t.section_name %></td>
        
       
        </tr>
      
        
        <% end %>
        

app/views/teachers/show.html.erb
<h1>Teacher Profile</h1>
<p>ID: <%= current_teacher.id %></p>
<p>Name: <%= current_teacher.name %></p>
<p>FatherName: <%= current_teacher.f_name %></p>
<p>Email: <%= current_teacher.email %></h1>
<p>PhoneNumber: <%= current_teacher.phone_number %></p>
<p>Date of Birth: <%= current_teacher.dob %></p>
<p>Address: <%= current_teacher.address %></p>

<%= link_to "Back", teacher_path %>

app/views/users/all_courses.html.erb
<h1>Enrolled Courses</h1>
<table id="enrollment" border="3" layout= "fixed" width=" 100%"  >
<tr>
    <th>ID</th>
    <th>Course</th>
    <th>Teacher Name</th>
    <th>Section</th>
    <th>Semester</th>
    <th>Semester No</th>
  </tr>

  <tr>
  <% @enrollments.each do |e| %>
        <td><%= e.id %></td>
        <td><%= e.section.course.course_name %></td>
        <td><%= e.section.teacher.name %></td>
        <td><%= e.section.section_name%></td>
        <td><%= e.semester.semester_type %></td>
        <td><%= e.semester.semester_number%></td>
  <% end %>
  </tr>

<%= link_to "Back", users_path %>

app/views/users/allcourses.html.erb
<h1>Enrolled Courses</h1>
<table id="enrollment" border="3" layout= "fixed" width=" 100%"  >
<tr>
    <th>ID</th>
    <th>Course</th>
    <th>Teacher Name</th>
    <th>Section</th>
    <th>Semester</th>
    <th>Semester No</th>
  </tr>


<% @enrollments.each do |e| %>
    <tr>
        <td><%= e.id %></td>
        <td><%= e.section.course.course_name %></td>
        <td><%= e.section.teacher.name %></td>
        <td><%= e.section.section_name%></td>
        <td><%= e.semester.semester_type %></td>
        <td><%= e.semester.semester_number%></td>
    </tr>
  <% end %>

<%= link_to "Back", users_path %>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= users_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      <li class="nav-item">
          <a class="nav-link active" href="<%= all_courses_user_path(current_user.id) %>">Courses</a>
        </li>
      <li class="nav-item">
        <a class="nav-link active" href="<%= transcript_user_path(current_user.id) %>">Transcript</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active " href="<%=user_path(current_user.id)%>" >Profile</a>
      </li>
        <li class="nav-item">
          <a class="nav-link active " href="<%= destroy_user_session_path %>" >Logout</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<h1>Student Profile</h1>
<p>ID: <%= current_user.id %></p>
<p>Name: <%= current_user.name %></p>
<p>FatherName: <%= current_user.f_name %></p>
<p>Email: <%= current_user.email %></h1>
<p>PhoneNumber: <%= current_user.phone_number %></p>
<p>Date of Birth: <%= current_user.dob %></p>
<p>Batch Number: <%= current_user.batch_id %></p>
<p>Semester Number: <%= current_user.enrollments.last.semester %></p>  

<%= link_to "Back", users_path %>

  

app/views/users/transcript.html.erb
<h1>Transcript</h1>
<table id="enrollment" border="3" layout= "fixed" width=" 100%"  >
<tr>
    <th>ID</th>
    <th>Course</th>
    <th>Section</th>
    <th>Semester Type</th>
    <th>Semester No</th>
    <th>Grade</th>
  </tr>


  <% @enrollments.each do |e| %>
        <tr>
          <td><%= e.id %></td>
          <td><%= e.section.course.course_name %></td>
          <td><%= e.section.section_name %></td>
          <td><%= e.semester.semester_type %></td>
          <td><%= e.semester.semester_number%></td>
          <td><%= e.grade.letter%></td>
        
          </tr>
  <% end %>
  
<%= link_to "Back", users_path %>